services:
  postgres:
    image: postgres:14
    container_name: urban_lens_db
    restart: always
    environment:
      POSTGRES_DB: urban_lens
      POSTGRES_USER: urban_lens
      POSTGRES_PASSWORD: urban_lens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urban_lens_network

networks:
  urban_lens_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 